spring:
  application:
    name: billify

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: false

# Custom JWT Properties
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${accessTokenExpiration}
  refresh-token-expiration: ${refreshTokenExpiration}

server:
  port: ${SERVER_PORT:8080}

frontend:
  url: ${FRONTEND_URL}

